services:
  postgres:
    image: postgres:latest
    container_name: database_service
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PAS}
    ports:
      - "${PORT_ONE}:${PORT_TWO}"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local